version: '3.3'
services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - './data/seq:/data'
    ports:
      - '5341:5341'
    image: 'datalust/seq:latest'
  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Fred1234"
      ACCEPT_EULA: "Y"